### PR TITLE
Modify the feedback field that can be confusing

### PR DESCRIPTION
**Pull request by AlexFaraino**
Some people though they had to type something in.
- Disabled the field
- Added a placeholder "Feedback..."

### CODE REVIEW

**Comment by gturri** [comment]
What about rather hiding this field when there's nothing in it (using e.g. the css property "display: none;")?
There would be no room for confusion anymore.

(also disabling the field would be be a good idea too)

**Comment by AlexFaraino** [comment]
Yeah, it would be a good idea, but it's not good for mobile phones : it will move the button on the screen if you zoomed.

**Comment by gturri** [comment]
So what about the css property "visibility: hidden"?

As far as I remember the element then wouldn't be displayed but would still use some space, so other items shouldn't move when the feedback field is shown / hidden

**Comment by AlexFaraino** [comment]
Done :)

**Comment by gturri** [comment]
Your PR seems nice. I just believe we should also change the visibility of the field in the `notRingingAnymore` function

**Comment by AlexFaraino** [comment]
I had another feedback tonight : we should display "Ringing" out of the
input. As simple text. It will be more visible on mobile phone.

And hide it again after 10sec.
Le 19 févr. 2014 23:15, "Guillaume Turri" notifications@github.com a
écrit :

**Comment by gturri** [comment]
Ok. Shall we also print the "someone is coming" feedback as simple text?

**Comment by AlexFaraino** [comment]
Done :)
I'll merge this pull request, as it now fits its purpose.

**Pull request merged**
